/* Variables */
variable "vpc_id" {}
variable "CIDR" {}
variable "sg_group_sql" {}
variable "db_subnet_id1" {}
variable "db_subnet_id2" {}
variable "db_subnet_grp_name_sql" {}
variable "inst_name_sql" {}
variable "db_name_sql" {}
variable "db_user_name_sql" {}
variable "db_user_password_sql" {}
variable "acs_key" {}
variable "sec_key" {}
variable "region" {}
variable "inst_type" {}
variable "inst_tag1" {}
variable "inst_tag2" {}
variable "inst_tag3" {}
variable "inst_tag4" {}
variable "avail_zone" {}
variable "pmtr_grp" {}
variable "eng_ver" {}
variable "mlt_az" {}
variable "maintain" {}
variable "bkp_win" {}
variable "rtn_prd" {}
variable "pub_access" {}
variable "PORT" {}
variable "stor" {}
