/* Variables */

variable "vpc_id" {}
variable "vpc_cidr" {}
variable "sg_group" {}
variable "sg_group_desc" {}
variable "redis_subnet_id1" {}
variable "redis_subnet_id2" {}
variable "redis_subnet_id3" {}
variable "subnet_group_name" {}
variable "subnet_group_desc" {}
variable "inst_name" {}
variable "inst_desc" {}
variable "inst_engine" {}
variable "inst_engine_version" {}
variable "inst_port" {}
variable "inst_parameter_group_name" {}
variable "inst_num_node_groups" {}
variable "inst_replicas_per_node_group" {}
variable "inst_maintenance_window" {}
variable "inst_backup_window" {}
variable "inst_snapshot_retention_limit" {}
variable "inst_failover" {}
variable "acs_key" {}
variable "sec_key" {}
variable "region" {}
variable "inst_type" {}
variable "avail_zone" {}
variable "inst_tag1" {}
variable "inst_tag2" {}
variable "inst_tag3" {}
variable "inst_tag4" {}
